FROM node:lts-alpine AS packages
WORKDIR /bookdress/packages

COPY ./packages /bookdress/packages

# Install dependencies for all internal packages
RUN set -e && \
  find ./ -mindepth 1 -maxdepth 1 -type d \
  -exec sh -c 'for dir; do \
    if [ -f "$dir/package.json" ]; then \
      echo "Installing dependencies in $dir"; \
      npm --prefix "$dir" install; \
    fi; \
  done' _ {} +


FROM node:lts-alpine AS build

WORKDIR /bookdress/api

COPY ./api/package*.json ./

RUN npm install --force && \
    npm cache clean --force

FROM node:lts-alpine
WORKDIR /bookdress/api

# Install curl for health checks
RUN apk add --no-cache curl

COPY --from=build /bookdress/api/node_modules ./node_modules

COPY --from=packages /bookdress/packages /bookdress/packages

COPY ./api ./
COPY ./api/.env.docker .env

EXPOSE 4002

CMD ["npm", "run", "dev"]
